### ISSUE TITLE
http://ecosystem.rubytogether.org/ - Ruby versions

### ISSUE THREAD

**Issue by MSP-Greg** [rubytogether/ecosystem#170]
I hate to ask, but the Ruby version data starts at 2.1, then jumps to 2.3.  Is that correct?

**Comment by sidk** [comment]
@MSP-Greg i believe 2.2 is part of "Others", but will double check this and get back to you.

**Comment by MSP-Greg** [comment]
@sidk

If it's easy to do, otherwise nevermind...

I was mostly thinking CI, as there aren't that many repos/gems testing on 2.1.  Then again, that may just be the 10% that won't upgrade until things go up in flames...

**Comment by juliana0101** [comment]
Está correto mas se você quiser podemos encontrar problemas

**Comment by juliana0101** [comment]
Estou aqui para ajudar, sou fã de códigos

**Comment by deivid-rodriguez** [comment]
I think the original question and answer were correct at the time, Rubies that don't explicitly appear are part of "Others". So this can be closed!
